Completed javascript-carousel Exercise.
annuhpark/rc0322-code-solutions pull request #69
Opened 2022-04-13 19:36 UTC by annuhpark

https://user-images.githubusercontent.com/69396309/163256704-d8be986d-71ad-419a-958b-acbfcb842d34.mov

2022-04-13 19:38 UTC, annuhpark commented
Also showing setInterval();

https://user-images.githubusercontent.com/69396309/163256955-e6250b55-af3a-4d08-bbcc-e6ee3333a3dc.mov

2022-04-13 19:42 UTC, TimelikeClosure requested changes
- Whenever the slide changes, the filled-in dot should change to match.
- When the user manually switches slides, the interval should start over.

2022-04-13 20:09 UTC, annuhpark commented
https://user-images.githubusercontent.com/69396309/163261852-8881e81f-3ffd-480f-b5b7-6400263deb1f.mov

2022-04-13 20:11 UTC, TimelikeClosure requested changes

2022-04-13 20:11 UTC, TimelikeClosure commented on javascript-carousel/main.js
> +setInterval(changeImage, 3000);
The countdown to automatically switch images should start over when the user manually changes it:

---

![image](https://user-images.githubusercontent.com/16143771/163262217-754925f3-0f2c-49ec-ac5e-d77134429560.png)

2022-04-14 00:14 UTC, TimelikeClosure approved these changes

2022-04-14 00:25 UTC, merged